name:                uno-simulator
version:             0.1.0.0
github:              "githubuser/Uno-simulator"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Uno-simulator#readme>

dependencies:
- base >= 4.7 && < 5
- random >= 1.2
- mtl >= 2.2.2
- lens
- HUnit >= 1.6.0.0


library:
  source-dirs: src

executables:
  uno-simulator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uno-simulator
    - random >= 1.2
    - mtl

tests:
  uno-simulator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uno-simulator
    - HUnit
